<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0"
				xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="text"/>

	<xsl:template match="configs"> 
\documentclass[12pt,a4paper,oneside]{letter}

\usepackage[left=25mm, right=20mm, top=20mm, bottom=20mm, paper=a4paper]{geometry}
\usepackage{times, hyperref}
\usepackage[ngerman]{babel}
\usepackage[utf8]{inputenc}
% remove the date generated by the doc class
\date{}
\address{\textbf{<xsl:value-of select="myname"/>} \\<xsl:value-of select="myaddress"/> \\ \href{mailto:<xsl:value-of select="myemail"/>}{<xsl:value-of select="myemail"/>} \\ <xsl:value-of select="myphone"/> }
\begin{document}
% the hspace could need some changing from letter to an other.
% to test the right amount of hspace you can place "\hspace{99mm} Lyon 14.04.2024 \\" in the beginning of the {} after\begin{letter}
%\begin{letter}{\firmName \\ \firmResponsible \\ \firmRespJob \\ \\[2\baselineskip] \hspace{99mm} \dateAndPlace  \\[2\baselineskip] \textbf{Bewerbung als \subjekt}}
\begin{letter}{<xsl:value-of select="firmName"/> \\  <xsl:value-of select="firmResponsible"/> \\ <xsl:value-of select="firmRespJob"/> \\ <xsl:value-of select="firmAddress"/> \\[2\baselineskip] \hspace{99mm} <xsl:value-of select="dateAndPlace"/> \\[2\baselineskip] \textbf{Bewerbung als <xsl:value-of select="subjekt"/>}}
%\firmResponsible
\opening{Sehr geehrte <xsl:value-of select="firmResponsible"/>,}
    
% Keiner dieser absatze sollte langer als sieben Zeilen sein. Einleitung ung Schluss jeweils am besten deutlich kurzer.

%Einleitung 
<xsl:value-of select="einleitung"/>


%Hauptteil eins 
    %Darstellung deiner Hard Skills
<xsl:value-of select="haupteileins"/>
%Hauptteil zwei
\\
\\
<xsl:value-of select="haupteilzwei"/>

%SoftSkills, Motivation und Leidenschaft 
%Schluss 
<xsl:value-of select="schluss"/>

Mit freundlichen Gr"u"sen, 
%better to have it writen with a pen
\\[\baselineskip]
<xsl:value-of select="myname"/>
\end{letter}

\end{document}

	</xsl:template> 

</xsl:stylesheet>



